// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinFormsApp_Report.Models;

[Keyless]
[Table("student")]
public partial class Student
{
    [Column("st_id")]
    public int? StId { get; set; }

    [Column("st_name")]
    [StringLength(100)]
    public string StName { get; set; }
}